### ISSUE TITLE
Required module is missing after installation

### ISSUE THREAD

**Issue by Takehiko2k** [Saltssaumure/AutoBeatPack#1]
Ossapi module is missing after installation from requirements.txt

![traceback](https://github.com/Osumatic/AutoBeatPack/assets/100091704/330cdc5f-f99b-40eb-953b-99645b040c96)

After installing it manually script works perfectly fine.

**Comment by Saltssaumure** [comment]
Seems to be fixed in [v0.3.1](https://github.com/Osumatic/AutoBeatPack/tree/v0.3.1)
